import { Message, TextGenerationOptions, ToolCall } from '../types';

/**
 * Built-in fake tool definitions for simulation.
 */
export const BUILTIN_TOOLS: Record<
  string,
  { args: Record<string, unknown>; result: Record<string, unknown> }
> = {
  get_weather: {
    args: { location: 'San Francisco, CA', unit: 'celsius' },
    result: { temperature: 19, condition: 'Partly Cloudy', humidity: 65 },
  },
  calculate: {
    args: { expression: '42 * 1337' },
    result: { result: 56154 },
  },
  search: {
    args: { query: 'latest AI trends' },
    result: {
      hits: [
        {
          title: 'State of AI 2026',
          snippet: 'AI models now excel in simulation and agentic coding.',
        },
      ],
    },
  },
};

/**
 * Generates a fake tool call matching requested tool or fallback.
 */
export function generateToolCall(options: TextGenerationOptions): ToolCall {
  const tools = options.tools;
  let toolName = 'get_weather';

  if (tools && tools.length > 0) {
    const firstTool = tools[0] as unknown as { name?: string; function?: { name?: string } };
    toolName = firstTool.function?.name || firstTool.name || 'get_weather';
  }

  const builtin = BUILTIN_TOOLS[toolName];
  const args = builtin
    ? JSON.stringify(builtin.args)
    : JSON.stringify({ query: 'sample argument value' });

  return {
    id: `call_${Math.random().toString(36).substring(2, 11)}`,
    type: 'function',
    function: {
      name: toolName,
      arguments: args,
    },
  };
}

/**
 * Generates a realistic text response based on messages/prompt and options.
 */
export function generateText(options: TextGenerationOptions): string {
  if (options.behavior?.invalidJson) {
    return '{"status": "error", "data": [incomplete_json...';
  }

  if (
    options.response_format?.type === 'json_object' ||
    options.response_format?.type === 'json_schema'
  ) {
    return JSON.stringify(
      {
        simulated: true,
        model: options.model,
        timestamp: new Date().toISOString(),
        message: 'This is a structured JSON response generated by the local Fake AI API Simulator.',
        data: {
          status: 'success',
          items: ['sample-item-1', 'sample-item-2', 'sample-item-3'],
        },
      },
      null,
      2
    );
  }

  // Extract last user message or prompt
  let lastUserContent = options.prompt || '';
  if (options.messages && options.messages.length > 0) {
    const userMsgs = options.messages.filter((m: Message) => m.role === 'user');
    const last = userMsgs[userMsgs.length - 1];
    if (last) {
      if (typeof last.content === 'string') {
        lastUserContent = last.content;
      } else if (Array.isArray(last.content)) {
        const textParts = last.content
          .filter((c) => c.type === 'text' && c.text)
          .map((c) => c.text);
        lastUserContent = textParts.join(' ');
      }
    }
  }

  if (options.behavior?.partialResponse) {
    return 'This is an interrupted partial response that';
  }

  if (lastUserContent.trim()) {
    return `Hello! This is a simulated AI response from the Fake AI API server.\n\nYou asked: "${lastUserContent.trim()}"\n\nEverything is working properly. You can test streaming, SDK compatibility, tool calling, and multimodal inputs seamlessly!`;
  }

  return `This is a test message generated by the Fake AI API Simulator running model "${options.model}". Streaming and completions are functioning normally.`;
}
